import = [
  "~/.config/alacritty/catppuccin-mocha.toml",
]

live_config_reload = true

[shell]
program = "zsh"
args = ["-l", "-c", "tmux a"]

[font]
normal = {family = "FiraCode Nerd Font"}
size = 14.0

[window]
decorations = "None"
