

[font]
normal = {family = "FiraCode Nerd Font"}
size = 14.0

[window]
decorations = "None"


[env]
TERM =  "xterm-256color"

[general]
live_config_reload = true
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[terminal]

shell.program = "zsh"
# shell.args = ["-l", "-c", "tmux a || tmux"]
