live_config_reload = true
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

shell.program = "zsh"
shell.args = ["-l", "-c", "tmux a || tmux"]


[font]
normal = {family = "FiraCode Nerd Font"}
size = 13.0

[window]
decorations = "None"


[env]
TERM =  "xterm-256color"
