[font]
normal = {family = "FiraCode Nerd Font"}
size = 10.0

[window]
decorations = "None"

[env]
TERM =  "xterm-256color"

[general]
live_config_reload = true
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[terminal]

shell.program = "zsh"
