[terminal.shell]
program = "zsh"
args = ["-l", "-c", "tmux a || tmux"]

[font]
normal = {family = "FiraCode Nerd Font"}
size = 11.0

[window]
decorations = "None"

[general]
live_config_reload = true
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM =  "xterm-256color"
